import 'dotenv/config';
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const products = [
  {
    name: '9 Pcs Pots & Pans Set',
    description: 'Premium quality 9-piece pots and pans set, perfect for everyday cooking. Includes multiple sizes suitable for all cooktops. Durable non-stick coating, ergonomic handles.',
    price: 65.0,
    originalPrice: null,
    stock: 50,
    category: 'Household Goods',
    badge: 'new',
    rating: 4.8,
    reviews: 142,
    itemCode: '8942',
    images: ['/images/product-pots-set.jpg'],
  },
  {
    name: '24 Pcs Cutlery Set',
    description: 'Elegant 24-piece stainless steel cutlery set. Includes 6 dinner forks, 6 dinner knives, 6 dessert spoons and 6 teaspoons. Mirror-polished finish. Dishwasher safe.',
    price: 22.95,
    originalPrice: 29.99,
    stock: 75,
    category: 'Household Goods',
    badge: 'sale',
    rating: 4.5,
    reviews: 87,
    itemCode: '9067',
    images: ['/images/product-cutlery.jpg'],
  },
  {
    name: 'Rattan Laundry Basket + Cover',
    description: 'Stylish woven rattan laundry basket with matching lid. Lightweight yet sturdy. Ideal for bedrooms and bathrooms. Holds a full wash load comfortably.',
    price: 19.5,
    originalPrice: null,
    stock: 40,
    category: 'Household Goods',
    badge: 'new',
    rating: 4.3,
    reviews: 53,
    itemCode: '9103',
    images: ['/images/product-laundry-basket.jpg'],
  },
  {
    name: 'Stand Patio Heater',
    description: 'Powerful 2kW stand patio heater. Keeps your outdoor space warm even on cool evenings. Easy-start ignition, adjustable height, includes safety tip-over switch.',
    price: 530.0,
    originalPrice: null,
    stock: 12,
    category: 'Outdoor Furniture',
    badge: null,
    rating: 4.9,
    reviews: 29,
    itemCode: '4262',
    images: ['/images/product-patio-heater.jpg'],
  },
  {
    name: 'Child Armchair',
    description: 'Adorable child-sized armchair, perfect for little ones. Soft upholstered finish, sturdy wooden frame. Suitable for children aged 2-6. Easy to clean fabric.',
    price: 4.25,
    originalPrice: null,
    stock: 100,
    category: 'Toys',
    badge: 'sale',
    rating: 4.1,
    reviews: 201,
    itemCode: '3441',
    images: ['/images/product-child-chair.jpg'],
  },
  {
    name: 'Bamboo Napkin Holder',
    description: 'Natural bamboo napkin holder with a minimalist design. Holds standard-sized napkins. Eco-friendly material. A beautiful addition to any dining table.',
    price: 18.0,
    originalPrice: null,
    stock: 60,
    category: 'Household Goods',
    badge: null,
    rating: 4.6,
    reviews: 44,
    itemCode: '9715',
    images: ['/images/product-napkin-holder.jpg'],
  },
  {
    name: '5 Step Aluminium Ladder',
    description: '5-step aluminium folding step ladder with non-slip rubber feet and anti-splay locking bar. Lightweight and easy to carry. Max load 150kg. Safety-certified.',
    price: 55.0,
    originalPrice: null,
    stock: 30,
    category: 'Household Goods',
    badge: 'new',
    rating: 4.7,
    reviews: 67,
    itemCode: '9659',
    images: ['/images/product-ladder.jpg'],
  },
  {
    name: 'Malta Luzzu Fridge Magnets (Set of 4)',
    description: 'Set of 4 colorful hand-painted fridge magnets featuring the iconic Maltese Luzzu fishing boat. A perfect souvenir or gift from Malta.',
    price: 7.95,
    originalPrice: null,
    stock: 200,
    category: 'Malta Souvenirs',
    badge: 'new',
    rating: 4.7,
    reviews: 63,
    itemCode: '5201',
    images: ['/images/category-souvenirs.jpg'],
  },
  {
    name: 'Hand-Painted Ceramic Malta Tile',
    description: 'Authentic hand-painted ceramic tile inspired by traditional Maltese art. Each piece is unique. Can be displayed as wall art or used as a trivet. 15cm x 15cm.',
    price: 14.5,
    originalPrice: 18.0,
    stock: 80,
    category: 'Malta Souvenirs',
    badge: 'sale',
    rating: 4.9,
    reviews: 41,
    itemCode: '5318',
    images: ['/images/category-souvenirs.jpg'],
  },
  {
    name: 'Luxury Scented Candle Gift Set',
    description: 'Beautiful gift set of 3 luxury soy wax candles in hand-crafted glass jars. Fragrances: Jasmine, Vanilla, and Sea Breeze. Long burn time of 45+ hours each.',
    price: 29.95,
    originalPrice: null,
    stock: 55,
    category: 'Gifts',
    badge: 'new',
    rating: 4.8,
    reviews: 95,
    itemCode: '6047',
    images: ['/images/category-gifts.jpg'],
  },
  {
    name: 'Premium Hamper Gift Box',
    description: 'Luxurious wicker hamper filled with premium treats including artisan biscuits, jam, honey, chocolates, and a bottle of Maltese wine. Perfect for any occasion.',
    price: 49.0,
    originalPrice: 59.0,
    stock: 20,
    category: 'Gifts',
    badge: 'sale',
    rating: 4.6,
    reviews: 38,
    itemCode: '6112',
    images: ['/images/category-gifts.jpg'],
  },
  {
    name: 'Garden Bistro Set (Table + 2 Chairs)',
    description: 'Elegant cast iron garden bistro set. Includes a round table (Ø 60cm) and 2 matching chairs. Weather-resistant finish. Perfect for balconies and small patios.',
    price: 189.0,
    originalPrice: null,
    stock: 15,
    category: 'Outdoor Furniture',
    badge: 'new',
    rating: 4.7,
    reviews: 55,
    itemCode: '4381',
    images: ['/images/category-outdoor.jpg'],
  },
  {
    name: 'Rattan Sun Lounger',
    description: 'Premium synthetic rattan sun lounger with weather-resistant cushions. 5-position backrest adjustment. Includes carry handle for easy transport. Max load 120kg.',
    price: 145.0,
    originalPrice: 179.0,
    stock: 18,
    category: 'Outdoor Furniture',
    badge: 'sale',
    rating: 4.5,
    reviews: 33,
    itemCode: '4419',
    images: ['/images/category-outdoor.jpg'],
  },
  {
    name: 'Folding Garden Chair (Set of 4)',
    description: 'Set of 4 sturdy folding garden chairs with steel frame and breathable mesh seat. Folds flat for compact storage. Suitable for indoor and outdoor use.',
    price: 79.95,
    originalPrice: null,
    stock: 25,
    category: 'Outdoor Furniture',
    badge: null,
    rating: 4.3,
    reviews: 78,
    itemCode: '4507',
    images: ['/images/category-outdoor.jpg'],
  },
  {
    name: 'Outdoor Storage Box 300L',
    description: '300-litre outdoor storage box made from UV-resistant resin. Weatherproof with secure lockable lid. Doubles as extra seating (max 200kg). Ideal for garden tools and cushions.',
    price: 64.5,
    originalPrice: null,
    stock: 22,
    category: 'Outdoor Furniture',
    badge: 'new',
    rating: 4.6,
    reviews: 41,
    itemCode: '4623',
    images: ['/images/category-outdoor.jpg'],
  },
  {
    name: 'Wooden Building Blocks Set (100 pcs)',
    description: '100-piece natural wooden building blocks set in various shapes and sizes. Promotes creativity and fine motor skills. Non-toxic paint. Suitable for ages 2+.',
    price: 24.99,
    originalPrice: null,
    stock: 90,
    category: 'Toys',
    badge: 'new',
    rating: 4.8,
    reviews: 134,
    itemCode: '3512',
    images: ['/images/category-toys.jpg'],
  },
  {
    name: 'Remote Control Racing Car',
    description: 'High-speed remote control racing car with 2.4GHz technology. Full proportional steering, 30mph top speed. Rechargeable battery included. Suitable for ages 6+.',
    price: 34.95,
    originalPrice: 44.95,
    stock: 45,
    category: 'Toys',
    badge: 'sale',
    rating: 4.4,
    reviews: 89,
    itemCode: '3678',
    images: ['/images/category-toys.jpg'],
  },
  {
    name: 'Arts & Crafts Activity Kit',
    description: 'Complete arts and crafts kit with paints, brushes, coloring pencils, stickers, glitter glue, and activity book. Stored in a handy carry case. Ages 4-10.',
    price: 18.5,
    originalPrice: null,
    stock: 65,
    category: 'Toys',
    badge: null,
    rating: 4.6,
    reviews: 62,
    itemCode: '3745',
    images: ['/images/category-toys.jpg'],
  },
  {
    name: 'Soft Plush Teddy Bear 40cm',
    description: 'Super soft and cuddly 40cm teddy bear made from premium plush fabric. Machine washable. Safe for all ages. Comes in a gift box. The perfect gift for any child.',
    price: 12.95,
    originalPrice: null,
    stock: 120,
    category: 'Toys',
    badge: 'new',
    rating: 4.9,
    reviews: 217,
    itemCode: '3802',
    images: ['/images/category-toys.jpg'],
  },
  {
    name: 'Maltese Cross Enamel Keyring',
    description: 'Beautifully crafted Maltese Cross keyring with colorful enamel inlay. Made from zinc alloy with a polished chrome finish. A timeless souvenir from Malta.',
    price: 5.5,
    originalPrice: null,
    stock: 300,
    category: 'Malta Souvenirs',
    badge: null,
    rating: 4.5,
    reviews: 108,
    itemCode: '5447',
    images: ['/images/category-souvenirs.jpg'],
  },
  {
    name: 'Malta Decorative Wall Plate',
    description: 'Hand-crafted decorative wall plate featuring a traditional Maltese design with intricate patterns and warm Mediterranean colors. Comes with wall mount. Diameter: 25cm.',
    price: 22.0,
    originalPrice: 27.0,
    stock: 35,
    category: 'Malta Souvenirs',
    badge: 'sale',
    rating: 4.7,
    reviews: 56,
    itemCode: '5563',
    images: ['/images/category-souvenirs.jpg'],
  },
  {
    name: 'Malta Filigree Silver Bracelet',
    description: 'Authentic Maltese filigree silver bracelet handcrafted by local artisans. Sterling silver 925. Adjustable length. Comes in a gift box. A truly unique Maltese keepsake.',
    price: 39.0,
    originalPrice: null,
    stock: 25,
    category: 'Malta Souvenirs',
    badge: 'new',
    rating: 4.8,
    reviews: 29,
    itemCode: '5691',
    images: ['/images/category-souvenirs.jpg'],
  },
  {
    name: 'Personalised Wooden Photo Frame',
    description: 'Beautiful solid wood photo frame with laser-engraved personalisation. Holds a 6x4 inch photo. Add a name, date, or short message. Makes a unique and meaningful gift.',
    price: 16.95,
    originalPrice: null,
    stock: 70,
    category: 'Gifts',
    badge: null,
    rating: 4.7,
    reviews: 143,
    itemCode: '6234',
    images: ['/images/category-gifts.jpg'],
  },
  {
    name: 'Spa Bath & Body Gift Set',
    description: 'Indulgent spa gift set including shower gel, body lotion, bath salts, and a loofah. Packaged in a beautiful organza bag. Fragranced with calming lavender and chamomile.',
    price: 35.0,
    originalPrice: 42.0,
    stock: 40,
    category: 'Gifts',
    badge: 'sale',
    rating: 4.5,
    reviews: 77,
    itemCode: '6358',
    images: ['/images/category-gifts.jpg'],
  },
  {
    name: "Gourmet Coffee Lover's Gift Set",
    description: 'The ultimate gift for coffee lovers. Includes 3 premium single-origin ground coffees, a ceramic mug, and a stainless steel spoon. Presented in an elegant gift box.',
    price: 44.95,
    originalPrice: null,
    stock: 30,
    category: 'Gifts',
    badge: 'new',
    rating: 4.6,
    reviews: 51,
    itemCode: '6471',
    images: ['/images/category-gifts.jpg'],
  },
  {
    name: 'Modern Ceramic Table Lamp',
    description: 'Elegant ceramic base table lamp with a linen shade. Warm ambient lighting perfect for living rooms and bedrooms. E27 bulb fitting. 45cm total height. Cable included.',
    price: 49.95,
    originalPrice: null,
    stock: 28,
    category: 'Home Decor',
    badge: 'new',
    rating: 4.8,
    reviews: 112,
    itemCode: '7101',
    images: ['/images/category-household.jpg'],
  },
  {
    name: 'Round Decorative Wall Mirror',
    description: 'Stunning round wall mirror with a minimalist metal frame in matte black. Diameter: 60cm. Can be hung vertically or horizontally. Adds depth and light to any room.',
    price: 64.0,
    originalPrice: 79.0,
    stock: 20,
    category: 'Home Decor',
    badge: 'sale',
    rating: 4.7,
    reviews: 88,
    itemCode: '7215',
    images: ['/images/category-household.jpg'],
  },
  {
    name: 'Scented Reed Diffuser Set',
    description: 'Long-lasting reed diffuser set with 200ml of premium fragrance oil and 8 natural rattan reeds. Fragrances: Cashmere & Musk, White Linen, Bergamot & Cedar.',
    price: 22.5,
    originalPrice: null,
    stock: 80,
    category: 'Home Decor',
    badge: null,
    rating: 4.6,
    reviews: 143,
    itemCode: '7334',
    images: ['/images/category-household.jpg'],
  },
  {
    name: 'Soft Velvet Throw Cushion Set (2pcs)',
    description: 'Set of 2 luxuriously soft velvet cushions in a contemporary design. 45x45cm with plump inner pad included. Available in: Blush Pink, Sage Green, Midnight Blue, Ivory.',
    price: 34.95,
    originalPrice: 42.0,
    stock: 55,
    category: 'Home Decor',
    badge: 'sale',
    rating: 4.5,
    reviews: 76,
    itemCode: '7448',
    images: ['/images/category-household.jpg'],
  },
  {
    name: 'Floating Wall Shelves Set of 3',
    description: 'Set of 3 minimalist floating wall shelves in natural oak veneer. Lengths: 60cm, 50cm, 40cm. Max load 8kg each. All fixings included. Perfect for displaying books and decor.',
    price: 38.0,
    originalPrice: null,
    stock: 35,
    category: 'Home Decor',
    badge: 'new',
    rating: 4.9,
    reviews: 201,
    itemCode: '7562',
    images: ['/images/category-household.jpg'],
  },
];

async function main() {
  console.log('[SEED] Starting database seed...');

  const deleted = await prisma.product.deleteMany();
  console.log(`[SEED] Cleared ${deleted.count} existing products`);

  for (const product of products) {
    const created = await prisma.product.create({ data: product });
    console.log(`  ✓ ${created.name} (${created.id})`);
  }

  console.log(`\n[SEED] Successfully seeded ${products.length} products`);
}

main()
  .catch((e) => {
    console.error('[SEED] Error:', e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
