export interface Product {
  id: string;
  name: string;
  price: number;
  originalPrice?: number;
  image: string;
  category: string;
  badge?: "new" | "sale" | "out-of-stock";
  rating: number;
  reviews: number;
  itemCode: string;
}

export interface Category {
  id: string;
  name: string;
  image: string;
  productCount: number;
  slug: string;
}

export const categories: Category[] = [
  { id: "1", name: "Household Goods", image: "/images/category-household.jpg", productCount: 245, slug: "household-goods" },
  { id: "2", name: "Gifts", image: "/images/category-gifts.jpg", productCount: 128, slug: "gifts" },
  { id: "3", name: "Toys", image: "/images/category-toys.jpg", productCount: 96, slug: "toys" },
  { id: "4", name: "Malta Souvenirs", image: "/images/category-souvenirs.jpg", productCount: 180, slug: "malta-souvenirs" },
  { id: "5", name: "Outdoor Furniture", image: "/images/category-outdoor.jpg", productCount: 72, slug: "outdoor-furniture" },
];

export const products: Product[] = [
  {
    id: "1",
    name: "9 Pcs Pots & Pans Set",
    price: 65.0,
    image: "/images/product-pots-set.jpg",
    category: "Household Goods",
    badge: "new",
    rating: 4.8,
    reviews: 142,
    itemCode: "8942",
  },
  {
    id: "2",
    name: "24 Pcs Cutlery Set",
    price: 22.95,
    originalPrice: 29.99,
    image: "/images/product-cutlery.jpg",
    category: "Household Goods",
    badge: "sale",
    rating: 4.5,
    reviews: 87,
    itemCode: "9067",
  },
  {
    id: "3",
    name: "Rattan Laundry Basket + Cover",
    price: 19.5,
    image: "/images/product-laundry-basket.jpg",
    category: "Household Goods",
    badge: "new",
    rating: 4.3,
    reviews: 53,
    itemCode: "9103",
  },
  {
    id: "4",
    name: "Stand Patio Heater",
    price: 530.0,
    image: "/images/product-patio-heater.jpg",
    category: "Outdoor Furniture",
    rating: 4.9,
    reviews: 29,
    itemCode: "4262",
  },
  {
    id: "5",
    name: "Child Armchair",
    price: 4.25,
    image: "/images/product-child-chair.jpg",
    category: "Toys",
    badge: "sale",
    rating: 4.1,
    reviews: 201,
    itemCode: "3441",
  },
  {
    id: "6",
    name: "Bamboo Napkin Holder",
    price: 18.0,
    image: "/images/product-napkin-holder.jpg",
    category: "Household Goods",
    rating: 4.6,
    reviews: 44,
    itemCode: "9715",
  },
  {
    id: "7",
    name: "5 Step Aluminium Ladder",
    price: 55.0,
    image: "/images/product-ladder.jpg",
    category: "Household Goods",
    badge: "new",
    rating: 4.7,
    reviews: 67,
    itemCode: "9659",
  },
  {
    id: "9",
    name: "Malta Luzzu Fridge Magnets (Set of 4)",
    price: 7.95,
    image: "/images/category-souvenirs.jpg",
    category: "Malta Souvenirs",
    badge: "new",
    rating: 4.7,
    reviews: 63,
    itemCode: "5201",
  },
  {
    id: "10",
    name: "Hand-Painted Ceramic Malta Tile",
    price: 14.5,
    originalPrice: 18.0,
    image: "/images/category-souvenirs.jpg",
    category: "Malta Souvenirs",
    badge: "sale",
    rating: 4.9,
    reviews: 41,
    itemCode: "5318",
  },
  {
    id: "11",
    name: "Luxury Scented Candle Gift Set",
    price: 29.95,
    image: "/images/category-gifts.jpg",
    category: "Gifts",
    badge: "new",
    rating: 4.8,
    reviews: 95,
    itemCode: "6047",
  },
  {
    id: "12",
    name: "Premium Hamper Gift Box",
    price: 49.0,
    originalPrice: 59.0,
    image: "/images/category-gifts.jpg",
    category: "Gifts",
    badge: "sale",
    rating: 4.6,
    reviews: 38,
    itemCode: "6112",
  },
  // Outdoor Furniture — 4 more to reach 5
  {
    id: "13",
    name: "Garden Bistro Set (Table + 2 Chairs)",
    price: 189.0,
    image: "/images/category-outdoor.jpg",
    category: "Outdoor Furniture",
    badge: "new",
    rating: 4.7,
    reviews: 55,
    itemCode: "4381",
  },
  {
    id: "14",
    name: "Rattan Sun Lounger",
    price: 145.0,
    originalPrice: 179.0,
    image: "/images/category-outdoor.jpg",
    category: "Outdoor Furniture",
    badge: "sale",
    rating: 4.5,
    reviews: 33,
    itemCode: "4419",
  },
  {
    id: "15",
    name: "Folding Garden Chair (Set of 4)",
    price: 79.95,
    image: "/images/category-outdoor.jpg",
    category: "Outdoor Furniture",
    rating: 4.3,
    reviews: 78,
    itemCode: "4507",
  },
  {
    id: "16",
    name: "Outdoor Storage Box 300L",
    price: 64.5,
    image: "/images/category-outdoor.jpg",
    category: "Outdoor Furniture",
    badge: "new",
    rating: 4.6,
    reviews: 41,
    itemCode: "4623",
  },
  // Toys — 4 more to reach 5
  {
    id: "17",
    name: "Wooden Building Blocks Set (100 pcs)",
    price: 24.99,
    image: "/images/category-toys.jpg",
    category: "Toys",
    badge: "new",
    rating: 4.8,
    reviews: 134,
    itemCode: "3512",
  },
  {
    id: "18",
    name: "Remote Control Racing Car",
    price: 34.95,
    originalPrice: 44.95,
    image: "/images/category-toys.jpg",
    category: "Toys",
    badge: "sale",
    rating: 4.4,
    reviews: 89,
    itemCode: "3678",
  },
  {
    id: "19",
    name: "Arts & Crafts Activity Kit",
    price: 18.5,
    image: "/images/category-toys.jpg",
    category: "Toys",
    rating: 4.6,
    reviews: 62,
    itemCode: "3745",
  },
  {
    id: "20",
    name: "Soft Plush Teddy Bear 40cm",
    price: 12.95,
    image: "/images/category-toys.jpg",
    category: "Toys",
    badge: "new",
    rating: 4.9,
    reviews: 217,
    itemCode: "3802",
  },
  // Malta Souvenirs — 3 more to reach 5
  {
    id: "21",
    name: "Maltese Cross Enamel Keyring",
    price: 5.5,
    image: "/images/category-souvenirs.jpg",
    category: "Malta Souvenirs",
    rating: 4.5,
    reviews: 108,
    itemCode: "5447",
  },
  {
    id: "22",
    name: "Malta Decorative Wall Plate",
    price: 22.0,
    originalPrice: 27.0,
    image: "/images/category-souvenirs.jpg",
    category: "Malta Souvenirs",
    badge: "sale",
    rating: 4.7,
    reviews: 56,
    itemCode: "5563",
  },
  {
    id: "23",
    name: "Malta Filigree Silver Bracelet",
    price: 39.0,
    image: "/images/category-souvenirs.jpg",
    category: "Malta Souvenirs",
    badge: "new",
    rating: 4.8,
    reviews: 29,
    itemCode: "5691",
  },
  // Gifts — 3 more to reach 5
  {
    id: "24",
    name: "Personalised Wooden Photo Frame",
    price: 16.95,
    image: "/images/category-gifts.jpg",
    category: "Gifts",
    rating: 4.7,
    reviews: 143,
    itemCode: "6234",
  },
  {
    id: "25",
    name: "Spa Bath & Body Gift Set",
    price: 35.0,
    originalPrice: 42.0,
    image: "/images/category-gifts.jpg",
    category: "Gifts",
    badge: "sale",
    rating: 4.5,
    reviews: 77,
    itemCode: "6358",
  },
  {
    id: "26",
    name: "Gourmet Coffee Lover's Gift Set",
    price: 44.95,
    image: "/images/category-gifts.jpg",
    category: "Gifts",
    badge: "new",
    rating: 4.6,
    reviews: 51,
    itemCode: "6471",
  },
];
